name: Build and deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NestApp
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf testedeploy
            mkdir testeploy
            cd testedeploy/
            git clone -b main https://github.com/luismaia-git/test-deploy.git backend
            cd backend
            npm i
            npm run build
            pm2 stop "me-formei-backend"
            pm2 delete "me-formei-backend"
            pm2 start dist/src/main.js --name "me-formei-backend"
            pm2 save
